# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HTML5 App Trainings
email: hello@mathiasmaier.de
description: 
baseurl: "/html5-app-training" # the subpath of your site, e.g. /blog
url: "http://mathiastim.github.io/html5-app-training/" # the base hostname & protocol for your site
twitter_username: mathiastim
github_username:  mathiastim

# Build settings
markdown: kramdown
